Naomi2 tti v1.0.0
NaomiProject/naomi-plugins pull request #20
Opened 2022-08-18 01:44 UTC by aaronchantrill

The Naomi2 TTI plugin is a simplified version of the Naomi TTI
intent parser. This version tries to use word frequencies to match
a specific template rather than to match a whole intent (which
contains many templates which may or may not all relate to the
same actual intention of the user).

For example, the old Naomi TTI had problems with templates that
were very similar to each other. The MPDControl command
"play <playlist>" and the Frotz command "play <game>" are very
similar, but in practive "play <game>" would always win even
though <playlist> is only associated with MPDControl just because
MPDControl has a bunch of other templates like "increase volume"
and "pause" which did not include the word "play" while every
template for Frotz did include the word "play".

"Tell me a joke" would also invariably choose a knock knock joke
since it had the only template that matched all of those words.

The new system will use Frotz to play a game or MPDControl to
play a playlist, and will choose a joke at random from the
different intents that include the words "tell me a ... joke".

Any feedback greatly appreciated.

2023-03-08 21:59 UTC, AustinCasteel requested changes
everything looks good except the source links to the wrong repo

2023-03-09 18:11 UTC, aaronchantrill commented
@AustinCasteel thank you for reviewing this. I have updated the URL in the readme.txt file.

2023-03-10 00:02 UTC, AustinCasteel approved these changes

2024-03-16 20:28 UTC, aaronchantrill commented
I believe I either ended up incorporating these changes into the base NaomiTTI engine or decided to abandon this approach. It's been so long I don't remember anymore. Closing.

2024-03-16 20:28 UTC, closed without merging